// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmvSPdOXPt9NRvlTLvpgNm6TlkQA1jHY',
    appId: '1:1037874011051:web:193354360eecdee0a850ee',
    messagingSenderId: '1037874011051',
    projectId: 'clothing-a',
    authDomain: 'clothing-a.firebaseapp.com',
    databaseURL: 'https://clothing-a-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuStSdKh-usT95ghaHTAbbxzkR8oU7Zjw',
    appId: '1:1037874011051:android:3dbd8c8de004fffaa850ee',
    messagingSenderId: '1037874011051',
    projectId: 'clothing-a',
    databaseURL: 'https://clothing-a-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZmvSPdOXPt9NRvlTLvpgNm6TlkQA1jHY',
    appId: '1:1037874011051:web:4f75f47f5ac19551a850ee',
    messagingSenderId: '1037874011051',
    projectId: 'clothing-a',
    authDomain: 'clothing-a.firebaseapp.com',
    databaseURL: 'https://clothing-a-default-rtdb.firebaseio.com',
    storageBucket: 'clothing-a.firebasestorage.app',
  );

}